Siyuan/requirement txt
SecurityLab-UCD/IRFuzzer pull request #45
Opened 2023-08-01 00:33 UTC by uilnauyisDP

Add requirements.txt into _scripts_ directory.

I collected dependencies with **pipreqs** module (https://pypi.org/project/pipreqs/) and verifies all dependencies are installed with command `pip3.8 install -r scripts/requirements.txt` with a fresh clone of IRFuzzer project.

2023-08-01 00:47 UTC, DataCorrupted requested changes

2023-08-01 00:47 UTC, DataCorrupted commented on README.md
>  pip3.8 install panda matplotlib
1. You can remove the `pip3.8 install <other stuff>`
2. I believe we have migrated to python3.10, so use `pip3.10` please.

2023-08-02 01:48 UTC, DataCorrupted approved these changes

2023-08-02 01:48 UTC, merged

2023-08-02 01:49 UTC, DataCorrupted commented
@uilnauyisDP I just realized to PR'ed against irfuzzer0.3. Can you PR again against master? Thanks.

2023-08-02 02:26 UTC, uilnauyisDP commented
@DataCorrupted  Should I have created the feature branch off the master branch and PR against master branch?